---
title: "HW 4 - Turtles"
subtitle: "Part 4 - Drafting Viz"
description: "Due Tue 03/11/2025" 
author: "Eva Newby"
toc: true
warning: false
message: false 
eval: true
echo: true
format:
  html:
    embed-resources: true
editor_options: 
  chunk_output_type: console
---


```{r}
# Load libraries
library(tidyverse)
library(here)
library(dplyr)
library(ggplot2)
library(sf)
library(ggspatial)
library(prettymapr)
library(rnaturalearth)
library(rnaturalearthdata)
library(forcats)
library(ggimage)
library(viridis)
library(viridisLite)
```

### Read in Turtle Nesting Data

```{r}
# Set the SHAPE_RESTORE_SHX config option
Sys.setenv("SHAPE_RESTORE_SHX" = "YES")

# Read the shapefile
shapefile_path <- "C:/MEDS/EDS240-dataviz/Assignments/newby-eds240-HW4/data/nestingbeaches_GCB.shp"
turtles <- st_read(shapefile_path) %>% 
    janitor::clean_names()
```

### Exploratory Data Analysis

```{r}
# Check CRS
st_crs(turtles)

# Unique Countries
unique(turtles$country)
```

### Clean and Wrangle Data

```{r}
# Get the bounding box for turtles
bbox <- st_bbox(turtles)
```

```{r}
# Assume data into regional names
turtles <- turtles %>% 
    mutate(region = case_when(rmu == 1 ~ "Caribbean and Gulf of Mexico",
                              rmu == 2 ~ "Southwest Atlantic",
                              rmu == 3 ~ "Southeast Atlantic",
                              rmu == 4 ~ "Mediterranean",
                              rmu == 5 ~ "Arabian",
                              rmu == 6 ~ "Western Indian",
                              rmu == 8 ~ "Eastern Indian",
                              rmu == 9 ~ "Western Pacific",
                              TRUE ~ "Unknown"))

# Set bounding boxes for each region, will need to adjust for each region
bbox_carib <- st_bbox(c(xmin = -98, ymin = 10, xmax = -60, ymax = 35), crs = st_crs(turtles))
                      
bbox_swat <- st_bbox(c(xmin = -80, ymin = -40, xmax = -30, ymax = 10), crs = st_crs(turtles))

bbox_seat <- st_bbox(c(xmin = -50, ymin = 0, xmax = 0, ymax = 40), crs = st_crs(turtles))

bbox_medit <- st_bbox(c(xmin = -10, ymin = 30, xmax = 40, ymax = 45), crs = st_crs(turtles))

bbox_arab <- st_bbox(c(xmin = 40, ymin = 10, xmax = 70, ymax = 30), crs = st_crs(turtles))

bbox_win <- st_bbox(c(xmin = 40, ymin = -20, xmax = 80, ymax = 10), crs = st_crs(turtles))

bbox_ein <- st_bbox(c(xmin = 80, ymin = -20, xmax = 110, ymax = 10), crs = st_crs(turtles))

bbox_wpa <- st_bbox(c(xmin = 110, ymin = -10, xmax = 150, ymax = 30), crs = st_crs(turtles))

# Save as list for easier access
bbox_list <- list(  "Caribbean and Gulf of Mexico" = bbox_carib,
                    "Southwest Atlantic"            = bbox_swat,
                    "Southeast Atlantic"            = bbox_seat,
                    "Mediterranean"                 = bbox_medit,
                    "Arabian"                       = bbox_arab,
                    "Western Indian"                = bbox_win,
                    "Eastern Indian"                = bbox_ein,
                    "Western Pacific"               = bbox_wpa)

# Add a new column so each entry has an assigned bbox
turtles <- turtles %>% 
    rowwise() %>% 
    mutate(bbox = list(bbox_list[[region]])) %>% 
    ungroup()
```

### Data Viz 1 - World Map

```{r}
# Q1: Where are sea turtles nesting? ---------------------------------------------------------------------------------

# View the nesting sites on a general basemap. interactive worldmap? geofacet package?
# Shadow the countries that have turtle nests. 
# Illuminate the beach locations in another color
overview_map <- ggplot()+
    annotation_map_tile()+
    geom_sf(data = turtles, color = '#438D80')+
    # add bounding box
    geom_rect(aes(xmin = bbox["xmin"], 
                  xmax = bbox["xmax"], 
                  ymin = bbox["ymin"], 
                  ymax = bbox["ymax"]),
              fill = NA) +
    coord_sf()+ # Change to Cartesian coordinates
    theme_void()+
    labs(title = "Turtle Nesting Locations (in green)")

overview_map
    
```

```{r}
# NEED HELP HERE
# Experimental caribbean map
# Get a world map as an sf object
# world <- ne_countries(scale = "medium", returnclass = "sf")
# 
# # Check for any invalid geometries
# st_is_valid(world)
# st_is_valid(turtles)
# 
# # fix invalid geometries in turtles
# library(lwgeom)
# turtles <- st_make_valid(turtles)
# 
# # Convert bbox to an sf polygon
# bbox_carib_sf <- st_as_sfc(bbox_carib)
# 
# # Ensure the polygon is valid
# bbox_carib_sf <- st_make_valid(bbox_carib_sf)
# 
# bbox_carib_sf <- st_make_valid(bbox_carib)
# 
# # bbox is bbox_carib
# caribbean_map <- st_crop(world, bbox_carib)
# 
# # Check CRS for both datasets
# st_crs(world) == st_crs(turtles)
# 
# 
# turtles_in_bbox <- st_crop(turtles, bbox_carib)


```

```{r}
# Experimental caribbean map, caribbean basemap data isn't showing up, need to dig into why, commented out for now.

# Create the ggplot map
carib_map <- ggplot() +
    geom_sf(data = turtles, color = '#438D80', size = 2)+
    #geom_sf(data = caribbean_map, fill = "lightblue") +
    coord_sf(xlim = c(bbox_carib["xmin"], bbox_carib["xmax"]),
           ylim = c(bbox_carib["ymin"], bbox_carib["ymax"]),
           expand = FALSE) +
    labs(title = "Caribbean and Gulf of Mexico",
       subtitle = "Using rnaturalearth and ggplot2",
       x = "Longitude", y = "Latitude") +
    theme_minimal()

carib_map
```

### Data Viz 2 - Bar Chart

```{r}
# Q2: Countries represented and their average nest count per year. ------------------------------------------------------------------------------- 
# per region
turtles %>% 
    ggplot(aes(x = fct_rev(fct_infreq(region)), 
               na.rm = TRUE))+
    geom_bar(fill = '#438D80')+
    geom_text(stat = 'count', 
              aes(label=after_stat(count)),
              hjust = -0.1,
              size = 4)+
    coord_flip()+
    labs(x = "",
         y = "Number of Nests",
         title = " Average Loggerhead Turtle Nesting Count by World Region (per year 1979 - 2023)")+
    theme_minimal()+
    theme(
        panel.grid.major.y = element_blank(),
         axis.text.y = element_text(size = 10),
        plot.title = element_text(hjust = 0.5))

    
```

### Exploratory Data Viz 3 - Point and Line Chart

```{r}
# Q3: Which regions that have nests have the highest variation in their mann-kendall slopes? ------------------------------------------------------

# # Mann-kendall plot per region
# turtles %>% 
#     ggplot(aes(x = mann_kendal, 
#                y = fct_rev(fct_infreq(region)), alpha = 0.2))+ # re-order to match the same order as the bar graph
#     geom_point(size = 4, # maybe find a little turtle guy instead of a round point?
#                color = '#438D80')+
#     geom_line(size = 2,
#               color = '#438D80')+ # I want to add a gradient to the line to indicate change. I'm thinking color scale red to green?
#     labs(title = 'Change in Loggerhead Turtle Nesting Trends by Region (1979 - 2023)',
#          x = " Change in Loggerhead Turtle Nesting Over Time (Mann-Kendall Slope)",
#          y = "")+
#     theme_minimal()+
#     theme(legend.position = 'none') 

#  Mann-kendall plot per region
turtle_icon <- "turtle-icon.png"

turtles %>%
  ggplot(aes(x = mann_kendal, 
             y = fct_rev(fct_infreq(region)))) +
  #geom_point(aes(image = turtle_icon), size = 1) + # Use ggimage for turtle icons - this isn't working that well
  geom_line(aes(color = mann_kendal), 
            size = 2) +  # Gradient color
  scale_color_gradient2(scale_color_viridis(option = "D")) + # look into why this isn't working
      #low = "lightblue", mid = "blue", high = "darkblue", midpoint = 0) + 
  geom_vline(xintercept = 0, color = "black", linetype = "dashed", size = 0.8, alpha = 0.5)+
  annotate("text", x = max(turtles$mann_kendal), y = 0, label = "No change in Nesting Trends", hjust = 1.2, vjust = -0.5, color = "black")+
  labs(title = 'Change in Loggerhead Turtle Nesting Trends by Region (1979 - 2023)',
       x = "Change in Loggerhead Turtle Nesting Over Time (Mann-Kendall Slope)",
       y = "") +
  theme_transparent() +
  theme(legend.position = 'none',
        # Sand colored background:
        panel.background = element_rect(fill = "#F4E7C5", color = NA),
        plot.background = element_rect(fill = "#F4E7C5", color = NA),
        legend.background = element_rect(fill = "#F4E7C5", color = NA)  
    )

```

```{r}
# this chunk is taking foreverrrr to run

ggplot(turtles, aes(x = mann_kendal, 
                    y = fct_rev(fct_infreq(region)))) +
    geom_image(aes(image = turtle_icon), 
               size = 0.5) + # Use your PNG image
    geom_line(aes(color = mann_kendal), 
              size = 2) +
    scale_color_gradient2(low = "green", 
                          mid = "lightblue", 
                          high = "blue", 
                          midpoint = 0) +
    labs(
        title = 'Change in Loggerhead Turtle Nesting Trends by Region (1979 - 2023)',
        x = "Change in Loggerhead Turtle Nesting Over Time (Mann-Kendall Slope)",
        y = ""
    ) +
    theme_minimal() +
    theme(legend.position = 'none')

```

